### ISSUE TITLE
Java api - scaleByPowerOfTen

### ISSUE THREAD

**Issue by zorba128** [epam/DFP#30]
1. Decimal64.scaleByPowerOfTen is not available (only in Decimal64Utils for underlying representation)
2. Decimal64Utils.scaleByPowerOfTen has wrong @Decimal annotation on the second (exponent, int) argument

**Comment by agdavydov81** [comment]
Thank you - will fix in next release.

**Comment by agdavydov81** [comment]
Pushed to master. Will be published soon.

**Comment by agdavydov81** [comment]
Fix published in 0.11.26.
