### ISSUE TITLE
API for RoundingMode.HALF_EVEN

### ISSUE THREAD

**Issue by yegodm** [epam/DFP#34]
`java.math.RoundingMode.HALF_EVEN` is very often used in financial calculations. The Intel library seems to provide it with `__bid64_round_integral_nearest_even` but it is not exposed through JNI and `Decimal64Utils/Decimal64`.

**Comment by agdavydov81** [comment]
@yegodm There is no big problem to export bid64_round_integral_nearest_even() to managed API.  
But note: all other math operations (e.g. add, mul, div) will be performed with BID_ROUNDING_TO_NEAREST flag.  
Is it acceptable for you?

**Comment by agdavydov81** [comment]
Fix published in 0.11.26.

The functions
`@Decimal public static long round(@Decimal final long value, final int n, final RoundType roundType)`
 refactoring will be performed soon.
