### ISSUE TITLE
Java: drop support of JDK 8

### ISSUE THREAD

**Issue by plokhotnyuk** [epam/DFP#76]
I propose using JDK 11 features like `Math.multiplyHigh` and `MethodHandles.byteArrayViewVarHandle` to speed up `JavaImpl*` functions for arithmetic operations, parsing and serialization of `Decimal64` numbers.

As an example the following code:
```scala
                long __CX = A;
                long __CY = T;
                long __CXH, __CXL, __CYH, __CYL, __PL, __PH, __PM, __PM2;
                __CXH = __CX >>> 32;
                __CXL = LONG_LOW_PART & __CX;
                __CYH = __CY >>> 32;
                __CYL = LONG_LOW_PART & __CY;

                __PM = __CXH * __CYL;
                __PH = __CXH * __CYH;
                __PL = __CXL * __CYL;
                __PM2 = __CXL * __CYH;
                __PH += (__PM >>> 32);
                __PM = (LONG_LOW_PART & __PM) + __PM2 + (__PL >>> 32);

                CA_w1 = __PH + (__PM >>> 32);
                CA_w0 = (__PM << 32) + (LONG_LOW_PART & __PL);
```
can be replaced by just 2 multiplication operations:
```scala
                CA_w1 = Math.multiplyHigh(A, T);
                CA_w0 = A * T;
```

**Comment by agdavydov81** [comment]
Hi!
I'll check the performance boost first.

**Comment by agdavydov81** [comment]
Thank you for interesting optimization point.

**Comment by plokhotnyuk** [comment]
`MethodHandles.byteArrayViewVarHandle` can be used for introducing SWAR (*S*IMD *W*ith *A* *R*egister) techniques that are used in [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/jvm/src/main/java/com/github/plokhotnyuk/jsoniter_scala/core/ByteArrayAccess.java).

**Comment by plokhotnyuk** [comment]
Please, also, check if the result of 2-nd multiplication is used.

As an example in `JavaImplDiv.bid64_div` the following code:
```java
                        long __CX = Q;
                        long __CY = bid_reciprocals10_64[nzeros];
                        long __CXH, __CXL, __CYH, __CYL, __PL, __PH, __PM, __PM2;
                        __CXH = __CX >>> 32;
                        __CXL = LONG_LOW_PART & __CX;
                        __CYH = __CY >>> 32;
                        __CYL = LONG_LOW_PART & __CY;

                        __PM = __CXH * __CYL;
                        __PH = __CXH * __CYH;
                        __PL = __CXL * __CYL;
                        __PM2 = __CXL * __CYH;
                        __PH += (__PM >>> 32);
                        __PM = (LONG_LOW_PART & __PM) + __PM2 + (__PL >>> 32);

                        CT_w1 = __PH + (__PM >>> 32);
                        CT_w0 = (__PM << 32) + (LONG_LOW_PART & __PL);
```
can be replaced just by a single multiplication because `CT_w0` is not used:
```java
                        CT_w1 = Math.multiplyHigh(Q, bid_reciprocals10_64[nzeros]);
```

**Comment by plokhotnyuk** [comment]
In some cases 2-nd multiplication is optional like in this optimized code for `JavaImplCmp.bid64_quiet_less`:
```java
        if (exp_x > exp_y) {    // to simplify the loop below,
            // otherwise adjust the x significand upwards
            // __mul_64x64_to_128MACH (sig_n_prime, sig_x, bid_mult_factor[exp_x - exp_y]); // @AD: Note: The __mul_64x64_to_128MACH macro is the same as __mul_64x64_to_128
            {
                final long __CY = bid_mult_factor[exp_x - exp_y];
                sig_n_prime_w1 = Math.multiplyHigh(sig_x, __CY);
                if (sig_n_prime_w1 != 0) {
                    return false;
                }
                sig_n_prime_w0 = sig_x * __CY;
            }

            // return 0 if values are equal
            if (sig_n_prime_w0 == sig_y) {
                return false;
            }
            // if positive, return whichever significand abs is smaller
            // (converse if negative)
            return UnsignedLong.isLess(sig_n_prime_w0, sig_y) ^ (x_mask_sign);
        }
```

**Comment by plokhotnyuk** [comment]
All comparisons like `UnsignedLong.isGreater(x, 0)` can be replaced by `x != 0`.

**Comment by agdavydov81** [comment]
isGreater(...) replacement is pushed to the same div10-speedup branch.
Thank you!!!

**Comment by agdavydov81** [comment]
The migration to the JDK9 is under discussion.
I believe, at least two LTS branches will be created: with support JDK1.7 and with support JDK1.11(or at least 1.9).

Thank you very mush: Math.multiplyHigh looks much faster than current implementation.

**Comment by plokhotnyuk** [comment]
@agdavydov81 Thanks for picking my ideas to work!

Waiting with impatience for the new release with all them implemented!

**Comment by agdavydov81** [comment]
@plokhotnyuk You absolutely right about Math.multiplyHigh: it operates with signed arguments, where as mantissa in DFP is stored as unsigned value limited to 9999999999999999 (0x2386F26FC0FFFF) maximal value.
So, in most cases __mul_64x64_to_128 can be safely replaced with Math.multiplyHigh, but this cases must be checked and tested carefully.

As for JDK11 migration, looks next version will be multi-release JAR, so not only Math.multiplyHigh, but also Math.unsignedMultiplyHigh could be used.

Thank you for your help!

**Comment by agdavydov81** [comment]
Hi!
JMH show no significant performance difference between Math.multiplyHigh and Math.unsignedMultiplyHigh (at least on my i7-1185G7), nor with JDK11 nor with JDK19 (both Eclipse Adoptium), so all direct multiplications where replaced with more safe unsignedMultiplyHigh call.

**Comment by agdavydov81** [comment]
Hi!
DFP 1.0.1 with you suggested optimizations has been released and published to Maven and Nuget.
https://github.com/epam/DFP/releases/tag/1.0.1
Many thanks for your help!
