### ISSUE TITLE
Please use Fixed-point notation for toString() methods

### ISSUE THREAD

**Issue by alex-karpovich** [epam/DFP#84]
Add ability to print 'integer' decimals with point, for example 1234 should be printed as 1234.0

**Comment by plokhotnyuk** [comment]
Should rules of formatting match with the implementation Java's `Double.toString`?

**Comment by agdavydov81** [comment]
Seems this is a main point.

**Comment by andymalakov** [comment]
Normally you expect .toString() output to match .parse() from string input format.

**Comment by agdavydov81** [comment]
The initial version of this fix is pushed to [issue84-to-string-as-double](https://github.com/epam/DFP/tree/issue84-to-string-as-double) branch.
Please review.
