### ISSUE TITLE
Revert issue #84: Restore original toString() formating and add toFloatString() function.

### ISSUE THREAD

**Issue by agdavydov81** [epam/DFP#91]
As discussed at the meeting with 
@andymalakov, @alex-karpovich, Alexei Osipov, Mikalai Dul, Barys Chupryn, Sergey Khotin and me,
The #84 must be reverted.
The original toString() integer values formatting style must be restored.
I.e. Decimal64.fromDouble(12340.0d).toString() must return "12340" instead of "12340.0"
and the separate function toFloatString() must be added with the current toString() behavior.

**Comment by pragyan140799** [comment]
Hi @agdavydov81  , I'm looking to contribute in open source projects. If you need I can look into this issue and fix.
Thank you

**Comment by plokhotnyuk** [comment]
> Hi @agdavydov81 , I'm looking to contribute in open source projects. If you need I can look into this issue and fix. Thank you

Hi @pragyan140799! 

Welcome to GitHub community! 

I have [a feature request to add decimal64 support in jsoniter-scala project](https://github.com/plokhotnyuk/jsoniter-scala/issues/1046). We can implement it together and probably contribute back some performance tricks for parsing and serialization of decimal64 here.

**Comment by pragyan140799** [comment]
> > Hi @agdavydov81 , I'm looking to contribute in open source projects. If you need I can look into this issue and fix. Thank you
> 
> Hi @pragyan140799!
> 
> Welcome to GitHub community!
> 
> I have [a feature request to add decimal64 support in jsoniter-scala project](https://github.com/plokhotnyuk/jsoniter-scala/issues/1046).
> 
> We can implement it together and probably contribute back some performance tricks for parsing and serialization of decimal64 here.

Hi @plokhotnyuk 

Sorry for the late reply and thank you for this oppoetunity.

If it's still available, we can start working.
